# Generated by Django 3.2.4 on 2021-06-22 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.campo', verbose_name='Matéria'),
        ),
    ]
