# Generated by Django 3.2.4 on 2021-06-15 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import paginas.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprovante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data', models.DateField()),
                ('data_final', models.DateField(blank=True, help_text='Informar apenas seo comprovante for relativo a um período.', null=True)),
                ('arquivo', models.FileField(upload_to=paginas.models.user_path)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paginas.atividade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
