# Generated by Django 3.2.4 on 2021-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0003_progressao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='data_final',
            field=models.DateField(blank=True, help_text='Informar apenas se o comprovante for relativo  a um período.', null=True),
        ),
    ]
