# Generated by Django 3.2.4 on 2021-06-16 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('paginas', '0004_alter_comprovante_data_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='progressao',
            name='observacao',
            field=models.TextField(verbose_name='Observação'),
        ),
    ]
