# Generated by Django 3.2.4 on 2021-06-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0005_auto_20210616_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='detalhes',
        ),
        migrations.RemoveField(
            model_name='atividade',
            name='numero',
        ),
        migrations.AddField(
            model_name='atividade',
            name='data',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='data_entrega',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
