# Generated by Django 3.2.4 on 2021-06-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0006_auto_20210616_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data',
        ),
    ]
