# Generated by Django 3.2.4 on 2021-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_remove_atividade_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='data_entrega',
        ),
        migrations.AddField(
            model_name='atividade',
            name='detalhes',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atividade',
            name='numero',
            field=models.IntegerField(default=2, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
