# Generated by Django 3.2.4 on 2021-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210622_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
